version: '3'
services:
  backend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tasksdb